name: EAS Update on Push

on:
  push:
    branches:
      - main  # Or 'master', depending on your repo

jobs:
  update:
    name: EAS Update
    runs-on: ubuntu-latest
    steps:
      - name: 🏗 Setup Repo
        uses: actions/checkout@v4

      - name: 🏗 Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18.x
          cache: 'npm' # Use 'yarn' or 'bun' if preferred

      - name: 🏗 Setup EAS
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: 📦 Install dependencies
        run: npm ci # Use 'yarn install --frozen-lockfile' if using yarn

      - name: 🚀 Publish Update
        run: eas update --branch production --message "Update from GitHub Actions"      